### ISSUE TITLE
Warning: Product could not be imported successfully and next process like  variations and reviews could not be imported, Please try it again!

### ISSUE THREAD

**Issue by MuhammadAmir1** [bagisto/laravel-aliexpress-dropship-chrome-extension#6] opened 2020-11-06 07:24 UTC
I'm using Bagisto v1.2.0, laravel-aliexpress-dropship-1.1.2, and latest aliexpress chrome extension 0.1.1. 

On submitting from edit product page, I get this error every time: Warning: Product could not be imported successfully and next process like  variations and reviews could not be imported, Please try it again!

Please guide me how to import?

**Comment by prateek-webkul** [comment] 2020-11-06 07:28
Hello @MuhammadAmir1 ,

Please update the aliexpress chrome extension from https://github.com/prateek-webkul/laravel-aliexpress-dropship-chrome-extension/tree/v1.2.0

Thanks

**Comment by MuhammadAmir1** [comment] 2020-11-06 10:53
I tested v1.20 but found the same error.

**Comment by prateek-webkul** [comment] 2020-11-06 10:55
@MuhammadAmir1 ,

Can you provide us the aliexpress product link for which you are placing order, for testing purpose..

Thanks

**Comment by MuhammadAmir1** [comment] 2020-11-06 11:00
I tried many products with epacket title or drop ship title
recently I tested:
https://www.aliexpress.com/item/1005001424484769.html?spm=a2g0o.productlist.0.0.29cc66ebwjAUUC&algo_pvid=d02e2f47-5ba3-4406-9e67-8347241a598b&algo_expid=d02e2f47-5ba3-4406-9e67-8347241a598b-5&btsid=0b0a555a16046596620122823e6796&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by MuhammadAmir1** [comment] 2020-11-06 13:27
Can you give me the product link you successfully imported last time with this version? So that I may try it thanks.

**Comment by MuhammadAmir1** [comment] 2020-11-07 11:21
@prateek-webkul Any solutions?

**Comment by prateek-webkul** [comment] 2020-11-07 11:33
We have recently got success with the product (https://www.aliexpress.com/item/4000910685605.html?spm=a2g0o.cart.0.0.5a483c00RW2t9G&mp=1) and checking for the product link you provided..

**Comment by prateek-webkul** [comment] 2020-11-07 11:40
@MuhammadAmir1 ,

Please attach the issue you are getting in placing an order. We recently checked with the product link you provided and got the success by completing order.

**Note:** You need to be login at aliexpress for completing order process..

**Comment by MuhammadAmir1** [comment] 2020-11-07 11:45
@prateek-webkul with this product you provided now no product edit page showing ... a one step before error. I'm already login with aliexpress account with google

**Comment by prateek-webkul** [comment] 2020-11-07 11:48
Can you share the screenshot of issue or small video of generating the issue, you are facing...

**Comment by MuhammadAmir1** [comment] 2020-11-07 12:48
![Screenshot (1)](https://user-images.githubusercontent.com/43962800/98441619-52b28280-2121-11eb-8f1d-e7bdbed538f7.png)

**Comment by MuhammadAmir1** [comment] 2020-11-07 12:48
![Screenshot (2)](https://user-images.githubusercontent.com/43962800/98441643-783f8c00-2121-11eb-9ae6-133feba4b82c.png)

**Comment by MuhammadAmir1** [comment] 2020-11-07 13:02
@prateek-webkul Can you tell what version you are using whome you succeeded in importing as I 'm unable to import even a single product. or am I doing wrong else where.

**Comment by prateek-webkul** [comment] 2020-11-07 13:22
@MuhammadAmir1 

Maybe the issue is aliexpress module version, please get it update from https://github.com/bagisto/laravel-aliexpress-dropship/tree/master. 

**Note:** Please run composer require laravel/helpers in root of your project.

**Comment by MuhammadAmir1** [comment] 2020-11-07 13:28
Ok thanks for your support I'll try and give you the feedback

**Comment by prateek-webkul** [comment] 2020-11-07 13:31
welcome and let us know if you face any other issues..

**Comment by MuhammadAmir1** [comment] 2020-11-12 12:03
Hi,
Today I again tried with a new project, everything up to date. when I submit on product update page, first time I get the message fetched successfully.
but actually no data is fetched and this message is received only one time and onward I get the message Warning: Product could not be imported successfully and next process like variations and reviews could not be imported, Please try it again

**Comment by MuhammadAmir1** [comment] 2020-11-12 12:05
I have checked storage link exists and storage permission is 775

**Comment by prateek-webkul** [comment] 2020-11-12 12:20
Please raise a ticket at support@bagisto.com.

**Comment by MuhammadAmir1** [comment] 2020-11-12 12:29
ok thanks

**Comment by prateek-webkul** [comment] 2021-02-01 04:54
@MuhammadAmir1 ,

Your query has been resolved over the ticket, so I am closing this issue.

**Closed as completed by prateek-webkul** 2021-02-01 04:54 UTC
